### ISSUE TITLE
panic with slice bounds out of range on select printer with default option

### ISSUE THREAD

**Issue by mponton** [pterm/pterm#419]
The logic here: https://github.com/pterm/pterm/blob/master/interactive_select_printer.go#L111 does not work as intended and will cause a panic if the default option index lies within `maxHeight` of the end of the `Options`. The issue can easily be reproduced by change the included `TestInteractiveSelectPrinter_Show` like this:

```go
func TestInteractiveSelectPrinter_Show(t *testing.T) {
	go func() {
		keyboard.SimulateKeyPress(keys.Up)
		keyboard.SimulateKeyPress(keys.Up)
		keyboard.SimulateKeyPress(keys.Enter)
	}()
	result, _ := pterm.DefaultInteractiveSelect.WithOptions([]string{"a", "b", "c", "d", "e"}).WithDefaultOption("e").Show()
	testza.AssertEqual(t, "c", result)
}
```

Running this test with the existing code you get:

```text
--- FAIL: TestInteractiveSelectPrinter_Show (0.00s)
panic: runtime error: slice bounds out of range [:8] with capacity 5 [recovered]
        panic: runtime error: slice bounds out of range [:8] with capacity 5

goroutine 9840 [running]:
testing.tRunner.func1.2({0x50f7a0, 0xc0002943d8})
        c:/go/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
        c:/go/src/testing/testing.go:1399 +0x39f
panic({0x50f7a0, 0xc0002943d8})
        c:/go/src/runtime/panic.go:884 +0x212
github.com/pterm/pterm.(*InteractiveSelectPrinter).Show(0xc000360000, {0x0, 0x0, 0x6a3260?})
        C:/Users/xt10816/Projects/github/mponton/pterm/interactive_select_printer.go:119 +0x985
github.com/pterm/pterm_test.TestInteractiveSelectPrinter_Show(0xc00030ad00?)
        C:/Users/xt10816/Projects/github/mponton/pterm/interactive_select_printer_test.go:19 +0x1b1
testing.tRunner(0xc00030aea0, 0x53aea0)
        c:/go/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
        c:/go/src/testing/testing.go:1493 +0x35f
exit status 2
FAIL    github.com/pterm/pterm  1.013s
```

I will send a PR to fix and reference this issue.

**Comment by MarvinJWendt** [comment]
Thanks! I'll look at your PR now :)
